# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('sex', models.CharField(max_length=4, null=True)),
                ('province', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Service')),
            ],
        ),
    ]
